export const POST_GET_ALL_POST = "FETCH_ALL_POST";
export const POST_GET_BY_ID = "FETCH_POST_BY_ID";
export const SEARCH_SUGGESTION = "SEARCH_SUGGESTION";
export const SEARCH_GET_SUGGESTION = "GET_SEARCH_SUGGESTION";
export const SEARCH_POST_BY_KEYWORD = "GET_POST_BY_KEYWORD";
export const SEARCH_COUNT_BY_KEYWORD = "FETCH_COUNT_BY_KEYWORD";

// export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID";
// export const SEARCH_SUGGESTION = "SEARCH_SUGGESTION";
// export const GET_SEARCH_SUGGESTION = "GET_SEARCH_SUGGESTION";
// export const GET_POST_BY_KEYWORD = "GET_POST_BY_KEYWORD";
// export const FETCH_COUNT_BY_KEYWORD = "FETCH_COUNT_BY_KEYWORD";